const fs=require('fs'), http=require('http'), path=require('path'), os=require('os'), assert=require('assert/strict'), {spawn}=require('child_process');
const root=__dirname, output=process.env.DSN_QA_DIR||'/tmp/dsn-qa';fs.mkdirSync(output,{recursive:true});
const server=http.createServer((req,res)=>{const file=path.join(root,req.url.split('?')[0]==='/'?'index.html':req.url.split('?')[0]);if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}fs.readFile(file,(e,data)=>{if(e){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.css':'text/css','.js':'text/javascript'})[path.extname(file)]||'text/plain');res.end(data);});});
const chrome=spawn('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check','--disable-background-networking','--disable-component-update','--disable-extensions','--disable-sync','--remote-debugging-pipe',`--user-data-dir=${fs.mkdtempSync(path.join(os.tmpdir(),'dsn-chrome-'))}`,'about:blank'],{stdio:['ignore','ignore','pipe','pipe','pipe']});
let seq=0, buffer='', pending=new Map(), errors=[],sid;
chrome.stderr.on('data',()=>{});
function cdp(method,params={},sessionId=sid){return new Promise((resolve,reject)=>{const id=++seq;const timer=setTimeout(()=>{pending.delete(id);reject(Error('Timed out: '+method));},15000);pending.set(id,{resolve,reject,timer});chrome.stdio[3].write(JSON.stringify({id,method,params,...(sessionId?{sessionId}:{})})+'\0');});}
chrome.stdio[4].on('data',chunk=>{buffer+=chunk;let i;while((i=buffer.indexOf('\0'))>=0){const raw=buffer.slice(0,i);buffer=buffer.slice(i+1);if(!raw)continue;const m=JSON.parse(raw);if(m.id&&pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);clearTimeout(p.timer);m.error?p.reject(Error(JSON.stringify(m.error))):p.resolve(m.result);}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.exception?.description||m.params.exceptionDetails.text);}});
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function ev(expression){const r=await cdp('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;}
async function until(expression){for(let i=0;i<100;i++){if(await ev(expression))return;await wait(100);}throw Error('Condition failed: '+expression);}
async function click(selector){const p=await ev(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});if(!e)throw Error('Missing element');e.scrollIntoView({block:'center',behavior:'instant'});const b=e.getBoundingClientRect();return {x:b.x+b.width/2,y:b.y+b.height/2};})()`);await cdp('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...p});await cdp('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...p});}
async function key(key,code=key,modifiers=0){await cdp('Input.dispatchKeyEvent',{type:'keyDown',key,code,modifiers,...(key==='a'&&modifiers===4?{commands:['selectAll']}:{}),windowsVirtualKeyCode:({ArrowDown:40,ArrowUp:38,Enter:13,Escape:27,Home:36,Backspace:8}[key]||key.toUpperCase().charCodeAt(0)),...(key.length===1&&!modifiers?{text:key}:{})});await cdp('Input.dispatchKeyEvent',{type:'keyUp',key,code,modifiers});}
async function fill(selector,text){await click(selector);await key('a','KeyA',4);await key('Backspace');if(text)await cdp('Input.insertText',{text});}
async function shot(name){await wait(300);fs.writeFileSync(path.join(output,name+'.png'),Buffer.from((await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:false})).data,'base64'));}
async function fit(){assert(await ev('document.documentElement.scrollWidth <= innerWidth+1'),'Horizontal overflow');}
async function viewport(width,height){await cdp('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:false});}
async function unlock(){await fill('#password','DsN');await click('#gate-form button');await until('!document.querySelector("#gate").open');}
async function reset(){await click('[data-category="all"]');if(await ev('onlySaved'))await click('#favorites-only');await fill('#search','');}
let checks=0;function ok(condition,message){assert(condition,message);checks++;console.log('PASS '+message);}
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const url=`http://127.0.0.1:${server.address().port}/`;
 const t=await cdp('Target.createTarget',{url:'about:blank'},null);sid=(await cdp('Target.attachToTarget',{targetId:t.targetId,flatten:true},null)).sessionId;
 await cdp('Runtime.enable');await cdp('Page.enable');await viewport(1440,1000);await cdp('Page.navigate',{url});await until('document.readyState==="complete" && typeof PLACES!=="undefined"');await ev('document.fonts.ready');
 await shot('desktop-gate');await key('Escape');ok(await ev('$("gate").open'),'Gate cannot escape');await fill('#password','wrong');await click('#gate-form button');ok(await ev('$("gate-error").textContent.includes("Not quite")'),'Wrong password feedback');await unlock();
 await ev('window.scrollTo({top:0,behavior:"instant"})');await shot('desktop-hero');await fit();
 ok(await ev('PLACES.length===63 && DATES.length===6'),'All 63 places and six dates loaded');
 ok(await ev('PLACES.find(p=>p.name==="The Original Fudge Kitchen").rating===100 && PLACES.find(p=>p.name==="Taco Bell").rating===12 && PLACES.find(p=>p.name==="Taverna Veranda").rating===null && PLACES.find(p=>p.name==="Venchi").visits===2'),'Special ratings and repeat preserved');
 for(const [cat,count] of [['vibes',8],['food',33],['drinks',13],['dessert',9]]){await click(`[data-category="${cat}"]`);ok(await ev('document.querySelectorAll(".place-card").length')===count,cat+' filter');}
 await reset();await fill('#search','joes');ok(await ev('document.querySelectorAll(".place-card").length===1 && $("places-grid").textContent.includes("Joe’s Pizza")'),'Punctuation-insensitive search');
 await fill('#search','nothing-matches-this');ok(await ev('!$("empty-state").hidden'),'Empty search state');await click('#reset');
 await click('#favorites-only');ok(await ev('!$("empty-state").hidden'),'Empty saved state');await click('#favorites-only');
 await click('[data-id="vibes-daintree-les-rooftop-bar"]');await click('#favorites-only');ok(await ev('document.querySelectorAll(".place-card").length===1'),'Saved-only filter');
 await cdp('Page.reload');await until('document.readyState==="complete" && typeof saved!=="undefined"');ok(await ev('saved.size===1 && !$("gate").open'),'Hearts and unlock survive reload');
 await click('#favorites-only');await click('[data-id="vibes-daintree-les-rooftop-bar"]');ok(await ev('saved.size===0 && !$("empty-state").hidden'),'Unsave from saved view');await click('#favorites-only');
 await click('[data-find="Junoon"]');ok(await ev('document.querySelectorAll(".place-card").length===1 && $("places-grid").textContent.includes("Junoon")'),'Spotlight find links');await shot('desktop-filtered');await reset();
 await ev('$("sort").value="rating";$("sort").dispatchEvent(new Event("change",{bubbles:true}))');await wait(100);ok(await ev('$("sort").value==="rating" && document.querySelector(".place-card h3").textContent.includes("Fudge")'),'Highest-rating sort');
 ok(await ev('[...document.querySelectorAll(".place-card h3")].at(-1).textContent.includes("Taverna")'),'Unrated sorted last');
 await ev('$("sort").value="name";$("sort").dispatchEvent(new Event("change",{bubbles:true}))');await wait(100);ok(await ev('$("sort").value==="name" && document.querySelector(".place-card h3").textContent.includes("AKKA")'),'Alphabetical sort');
 await ev('$("sort").value="low";$("sort").dispatchEvent(new Event("change",{bubbles:true}))');await wait(100);ok(await ev('$("sort").value==="low" && document.querySelector(".rating").textContent.startsWith("0")'),'Lowest-rating sort');
 await click('#pick-date');await shot('desktop-date-dialog');const pick=await ev('currentPick');await click('#repick');ok(await ev('currentPick')!==pick,'Date reroll changes pick');await key('Escape');ok(await ev('!$("date-dialog").open'),'Escape dismisses date dialog');
 await click('#pick-date-bottom');await click('#see-list');ok(await ev('document.activeElement.id==="pick-date-bottom"'),'Date list link and focus');
 for(const id of ['brooklyn-flea','musical','farmers-market','broad-nosh','punjab-meet'])await click(`input[value="${id}"]`);
 await click('#pick-date-bottom');ok(await ev('currentPick==="batsu" && $("repick").disabled'),'Jar excludes completed dates');await click('#close-date');await click('input[value="batsu"]');await click('#pick-date-bottom');ok(await ev('currentPick===null && $("picked-name").textContent.includes("chapter")'),'All dates completed state');await click('#close-date');
 await cdp('Page.reload');await until('document.readyState==="complete" && typeof done!=="undefined"');ok(await ev('done.size===6 && $("date-progress").textContent==="6 / 6"'),'Checklist survives reload');
 for(const id of ['brooklyn-flea','musical','farmers-market','broad-nosh','punjab-meet','batsu'])await click(`input[value="${id}"]`);ok(await ev('done.size===0'),'Checklist undo');await shot('desktop-dates');
 for(const width of [390,320,768]){await viewport(width,844);await ev('window.scrollTo({top:0,behavior:"instant"})');await fit();await shot('hero-'+width);await click('[data-category="food"]');await fit();await shot('book-'+width);await click('#pick-date-bottom');await fit();await shot('dialog-'+width);await click('#close-date');}
 await viewport(390,844);await click('input[value="musical"]');await shot('mobile-dates');await click('input[value="musical"]');
 await click('#lock-footer');ok(await ev('$("gate").open && $("site").inert'),'Lock hides access to controls');await shot('mobile-gate');await unlock();
 await cdp('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});ok(await ev('getComputedStyle(document.querySelector(".steam")).animationName==="none"'),'Reduced motion respected');
 await viewport(1440,1000);await ev('document.documentElement.style.zoom="2"');await fit();await ev('document.documentElement.style.zoom=""');
 await click('a[href="archive.html"]');await until('document.title.includes("Archive")');ok(await ev('document.body.textContent.includes("CHICAGO")'),'Archive preserved');await until('!document.getElementById("pw-gate")');await click('a[href="index.html"]');await until('document.title.includes("autumn")');
 // Deliberately stage malformed persisted data, then exercise normal reload and unlock.
 await ev('localStorage.setItem("dsn-fall-hearts-v1","{broken");localStorage.setItem("dsn-fall-dates-v1",JSON.stringify({bad:true}))');await cdp('Page.reload');await until('document.readyState==="complete" && typeof saved!=="undefined"');ok(await ev('saved.size===0 && done.size===0'),'Malformed storage is tolerated');
 const block=await cdp('Page.addScriptToEvaluateOnNewDocument',{source:'Storage.prototype.setItem=function(){throw new Error("Blocked storage")};Storage.prototype.getItem=function(){throw new Error("Blocked storage")};Storage.prototype.removeItem=function(){throw new Error("Blocked storage")};'});await cdp('Page.reload');await until('document.readyState==="complete" && typeof PLACES!=="undefined"');await unlock();await click('[data-id="vibes-daintree-les-rooftop-bar"]');ok(await ev('saved.size===1 && $("toast").textContent.includes("unavailable")'),'Blocked storage stays usable with honest feedback');await cdp('Page.removeScriptToEvaluateOnNewDocument',{identifier:block.identifier});
 ok(errors.length===0,'No browser exceptions');console.log(JSON.stringify({checks,screenshots:output}));
})().catch(async e=>{console.error(e.stack);try{console.error('STATE',await ev('({sort:$("sort")?.value,active:document.activeElement.outerHTML,top:document.querySelector(".place-card h3")?.textContent})'));await shot('failure');}catch{}process.exitCode=1;}).finally(()=>{chrome.kill();server.close();for(const p of pending.values())clearTimeout(p.timer);});
